### ISSUE TITLE
Show sv_hostname of server in title

### ISSUE THREAD

**Issue by lukeb2e** [icedream/icecon#3]
Show a cleaned sv_hostname in title when connected to a server.

Eg: `IceCon - Fancy Servername`

**Comment by icedream** [comment]
There's one particular problem with this issue and that is that while Icecon supports Q3-like servers (which usually implement the `sv_hostname` variable), not all such compatible servers will guaranteed provide this variable. This may end up getting scrapped in order to provide simplified functionality over hacks.

Also this requires implementing asynchronous variable polling which I'm also not too sure about ever since this issue was opened...

**Comment by lukeb2e** [comment]
Alternatively show the IP:Port of the connected server.

**Comment by icedream** [comment]
I've decided to go for displaying the address in the title bar. This will be part of the 1.0.1 release.
